
CREATE DATABASE `PROJETO` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

use PROJETO;

CREATE TABLE `CLIENTE` (
  `NOME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SEXO` char(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CPF` int DEFAULT NULL,
  `TELEFONE` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENDERECO` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO PROJETO.CLIENTE
(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
INSERT INTO PROJETO.CLIENTE
(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO PROJETO.CLIENTE
(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('JORGE', 'M', 'JORGE@IG.COM.BR', 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');
INSERT INTO PROJETO.CLIENTE
(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('LILIAN', 'F', 'LILIAN@HOTMAIL.COM', 887774856, '947785696', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ');
INSERT INTO PROJETO.CLIENTE
(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO)
VALUES('CARLA', 'F', 'CARLA@TERATI.COM.BR', 7745828, '66587458', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');